name: 3-action checkout demo - multi events filter
on: 
  push:
    branches:
      - '*'
      - '!main'
  pull_request:
    branches:
      - 'releases/**'   
  workflow_dispatch:
  
  
jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4


      - name: install pytest
        run: pip install pytest
      - name: run pytest
        run: pytest
