name: 2-action checkout demo - multi events filter
on: push

  
  
jobs:
  pytest:
    runs-on: ubuntu-latest
    if:
      contains('
        refs/heads/dev
      ', github.ref)

    steps:
      - name: checkout code
        uses: actions/checkout@v4


      - name: install pytest
        run: pip install pytest
      - name: run pytest
        run: pytest
